nav:
- 홈: index.md
- 기사 모음:
  - 2025년:
    - 07월:
      - 파충류의 내면 세계: articles/2025/07/2025-07-11_파충류의_내면_세계.md
      - 파도가 지구를 형성하는 방식: articles/2025/07/2025-07-11_파도가_지구를_형성하는_방식.md
      - 중국의 에너지 지배력을 보여주는 3가지 차트: articles/2025/07/2025-07-11_중국의_에너지_지배력을_보여주는_3가지_차트.md
      - 재난 대응을 앞당길 수 있는 사이보그 딱정벌레: articles/2025/07/2025-07-11_재난_대응을_앞당길_수_있는_사이보그_딱정벌레.md
      - 이 네 발 로봇이 온몸을 사용해 던지기를 배웠습니다: articles/2025/07/2025-07-11_이_네_발_로봇이_온몸을_사용해_던지기를_배웠습니다.md
      - 소리를 이용해 감지하는 로봇 팔: articles/2025/07/2025-07-11_소리를_이용해_감지하는_로봇_팔.md
      - 세상의 상태가 당신에게 고통을 주고 있나요?: articles/2025/07/2025-07-11_세상의_상태가_당신에게_고통을_주고_있나요?.md
      - '변화하는 힘: 암흑 에너지에 대한 논쟁의 발전': articles/2025/07/2025-07-11_변화하는_힘:_암흑_에너지에_대한_논쟁의_발전.md
      - 미술을 위한 Ai 보호장치의 약점과 Ai 규제에 대한 인식 변화: articles/2025/07/2025-07-11_미술을_위한_AI_보호장치의_약점과_AI_규제에_대한_인식_변화.md
      - 과학자들, 처음부터 인간 게놈 전체를 합성하는 도전적인 프로젝트 시작: articles/2025/07/2025-07-11_과학자들,_처음부터_인간_게놈_전체를_합성하는_도전적인_프로젝트_시작.md
      - 공기 중에서 물을 끌어내는 장치   죽음의 계곡에서도 작동: articles/2025/07/2025-07-11_공기_중에서_물을_끌어내는_장치_-_죽음의_계곡에서도_작동.md
      - Ai 모델의 이미지 학습을 방해하는 보호 기술을 제거하는 도구: articles/2025/07/2025-07-11_AI_모델의_이미지_학습을_방해하는_보호_기술을_제거하는_도구.md
      - 피라미드 건설을 지탱했던 빵 만들기: articles/2025/07/2025-07-10_피라미드_건설을_지탱했던_빵_만들기.md
      - 재난 대응에 사이보그 딱정벌레가 도움이 될 수 있는 미래: articles/2025/07/2025-07-10_재난_대응에_사이보그_딱정벌레가_도움이_될_수_있는_미래.md
      - 인공지능 규제 유예 법안의 좌절이 새로운 정치 시대를 예고할 수 있는 이유: articles/2025/07/2025-07-10_인공지능_규제_유예_법안의_좌절이_새로운_정치_시대를_예고할_수_있는_이유.md
      - 이 사족 로봇이 전신을 사용해 던지는 것을 보여줍니다: articles/2025/07/2025-07-10_이_사족_로봇이_전신을_사용해_던지는_것을_보여줍니다.md
      - 웹에서 발견한 이 주의 최신 기술 이야기들: articles/2025/07/2025-07-10_웹에서_발견한_이_주의_최신_기술_이야기들.md
      - '오픈Ai 제국의 내부: 카렌 하오와의 대화': articles/2025/07/2025-07-10_오픈AI_제국의_내부:_카렌_하오와의_대화.md
      - 오래 살기 위해서는 머리에 있는 것일 수도 있다: articles/2025/07/2025-07-10_오래_살기_위해서는_머리에_있는_것일_수도_있다.md
      - 시간이란 무엇일까?: articles/2025/07/2025-07-10_시간이란_무엇일까?.md
      - 소리를 통해 "느끼는" 로봇 팔: articles/2025/07/2025-07-10_소리를_통해_"느끼는"_로봇_팔.md
      - '변화하는 힘: 암흑 에너지에 대한 토론의 진화': articles/2025/07/2025-07-10_변화하는_힘:_암흑_에너지에_대한_토론의_진화.md
      - 과학자들, 인간 유전체를 처음부터 만들기 위한 대규모 프로젝트 시작: articles/2025/07/2025-07-10_과학자들,_인간_유전체를_처음부터_만들기_위한_대규모_프로젝트_시작.md
      - 'Openai 제국에 대한 대화: Karen Hao와의 대화': articles/2025/07/2025-07-10_OpenAI_제국에_대한_대화:_Karen_Hao와의_대화.md
site_name: Singularity Daily
theme:
  extra_css:
  - stylesheets/extra.css
  name: material
